server:
  port: 8080

spring:
  kafka:
    bootstrap-severs: ${KAFKA_BROKER:localhost:9092}
    consumer:
      group-id: orchestrator-group
      auto-offset-reset: latest

logging:
  level:
    root: DEBUG